In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
import matplotlib
%matplotlib inline

df1 = pd.read_csv('../data/raw/world_happiness_report.csv')

print(df1)

      Unnamed: 0  Happiness Rank      Country  \
0              0               1  Switzerland
1              1               2      Iceland
2              2               3      Denmark
3              3               4       Norway
4              4               5       Canada
...          ...             ...          ...
1224         141             142    Botswana*
1225         142             143      Rwanda*
1226         143             144     Zimbabwe
1227         144             145      Lebanon
1228         145             146  Afghanistan

                               Region Happiness Score  \
0                      Western Europe           7.587
1                      Western Europe           7.561
2                      Western Europe           7.527
3                      Western Europe           7.522
4                       North America           7.427
...                               ...             ...
1224                                -           3,471
1225                                -           3,268
1226               Sub-Saharan Africa           2,995
1227  Middle East and Northern Africa           2,955
1228                    Southern Asia           2,404

     Economy (GDP per Capita) Family (Social Support)  \
0                     1.39651                 1.34951
1                     1.30232                 1.40223
2                     1.32548                 1.36058
3                       1.459                 1.33095
4                     1.32629                 1.32261
...                       ...                     ...
1224                    1,503                   0,815
1225                    0,785                   0,133
1226                    0,947                   0,690
1227                    1,392                   0,498
1228                    0,758                   0,000

     Health (Life Expectancy)  Freedom Trust (Government Corruption)  \
0                     0.94143  0.66557                       0.41978
1                     0.94784  0.62877                       0.14145
2                     0.87464  0.64938                       0.48357
3                     0.88521  0.66973                       0.36503
4                     0.90563  0.63297                       0.32957
...                       ...      ...                           ...
1224                    0,280    0,571                         0,102
1225                    0,462    0,621                         0,544
1226                    0,270    0,329                         0,105
1227                    0,631    0,103                         0,034
1228                    0,289    0,000                         0,005

     Generosity  Year
0       0.29678  2015
1        0.4363  2015
2       0.34139  2015
3       0.34699  2015
4       0.45811  2015
...         ...   ...
1224      0,012  2022
1225      0,187  2022
1226      0,106  2022
1227      0,082  2022
1228      0,089  2022

[1229 rows x 12 columns]

In [ ]:
d1 = df1.shape
d2 = df1.head()
d3 = df1.columns
print(d1)
print(d2)
print(d3)

(1229, 12)
   Unnamed: 0  Happiness Rank      Country          Region Happiness Score  \
0           0               1  Switzerland  Western Europe           7.587
1           1               2      Iceland  Western Europe           7.561
2           2               3      Denmark  Western Europe           7.527
3           3               4       Norway  Western Europe           7.522
4           4               5       Canada   North America           7.427

  Economy (GDP per Capita) Family (Social Support) Health (Life Expectancy)  \
0                  1.39651                 1.34951                  0.94143
1                  1.30232                 1.40223                  0.94784
2                  1.32548                 1.36058                  0.87464
3                    1.459                 1.33095                  0.88521
4                  1.32629                 1.32261                  0.90563

   Freedom Trust (Government Corruption) Generosity  Year
0  0.66557                       0.41978    0.29678  2015
1  0.62877                       0.14145     0.4363  2015
2  0.64938                       0.48357    0.34139  2015
3  0.66973                       0.36503    0.34699  2015
4  0.63297                       0.32957    0.45811  2015
Index(['Unnamed: 0', 'Happiness Rank', 'Country', 'Region', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family (Social Support)',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Year'],
      dtype='object')

In [ ]:
print(df1['Year'].unique())

[2015 2016 2017 2018 2019 2020 2021 2022]

In [ ]:
df1 = df1[df1.Year != 2022]

df1

,Unnamed: 0,Happiness Rank,Country,Region,Happiness Score,Economy (GDP per Capita),Family (Social Support),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Year
0,0,1,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,1,2,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.4363,2015
2,2,3,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,3,4,Norway,Western Europe,7.522,1.459,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,4,5,Canada,North America,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
1078,144,145,Lesotho,Sub-Saharan Africa,3.512,0.451,0.731,0.007,0.405,0.015,0.103,2021
1079,145,146,Botswana,Sub-Saharan Africa,3.467,1.099,0.724,0.34,0.539,0.088,0.027,2021
1080,146,147,Rwanda,Sub-Saharan Africa,3.415,0.364,0.202,0.407,0.627,0.493,0.227,2021
1081,147,148,Zimbabwe,Sub-Saharan Africa,3.145,0.457,0.649,0.243,0.359,0.075,0.157,2021
1082,148,149,Afghanistan,South Asia,2.523,0.37,0.0,0.126,0.0,0.01,0.122,2021

In [ ]:
df1 = df1.copy().drop(['Happiness Rank','Freedom','Trust (Government Corruption)', 'Generosity'], axis=1)
df1

,Unnamed: 0,Country,Region,Happiness Score,Economy (GDP per Capita),Family (Social Support),Health (Life Expectancy),Year
0,0,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,2015
1,1,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,2015
2,2,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,2015
3,3,Norway,Western Europe,7.522,1.459,1.33095,0.88521,2015
4,4,Canada,North America,7.427,1.32629,1.32261,0.90563,2015
...,...,...,...,...,...,...,...,...
1078,144,Lesotho,Sub-Saharan Africa,3.512,0.451,0.731,0.007,2021
1079,145,Botswana,Sub-Saharan Africa,3.467,1.099,0.724,0.34,2021
1080,146,Rwanda,Sub-Saharan Africa,3.415,0.364,0.202,0.407,2021
1081,147,Zimbabwe,Sub-Saharan Africa,3.145,0.457,0.649,0.243,2021
1082,148,Afghanistan,South Asia,2.523,0.37,0.0,0.126,2021

In [ ]:
df1= df1.copy().drop(df1.columns[0], axis=1)
print(df1.shape)
df1

(1083, 7)

,Country,Region,Happiness Score,Economy (GDP per Capita),Family (Social Support),Health (Life Expectancy),Year
0,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,2015
1,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,2015
2,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,2015
3,Norway,Western Europe,7.522,1.459,1.33095,0.88521,2015
4,Canada,North America,7.427,1.32629,1.32261,0.90563,2015
...,...,...,...,...,...,...,...
1078,Lesotho,Sub-Saharan Africa,3.512,0.451,0.731,0.007,2021
1079,Botswana,Sub-Saharan Africa,3.467,1.099,0.724,0.34,2021
1080,Rwanda,Sub-Saharan Africa,3.415,0.364,0.202,0.407,2021
1081,Zimbabwe,Sub-Saharan Africa,3.145,0.457,0.649,0.243,2021
1082,Afghanistan,South Asia,2.523,0.37,0.0,0.126,2021

In [ ]:
df1["Happiness Score"]=df1["Happiness Score"].astype(float)
df1["Economy (GDP per Capita)"]=df1["Economy (GDP per Capita)"].astype(float)
df1["Family (Social Support)"]=df1["Family (Social Support)"].astype(float)
df1["Health (Life Expectancy)"]=df1["Health (Life Expectancy)"].astype(float)

In [ ]:
df1

,Country,Region,Happiness Score,Economy (GDP per Capita),Family (Social Support),Health (Life Expectancy),Year
0,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,2015
1,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,2015
2,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,2015
3,Norway,Western Europe,7.522,1.45900,1.33095,0.88521,2015
4,Canada,North America,7.427,1.32629,1.32261,0.90563,2015
...,...,...,...,...,...,...,...
1078,Lesotho,Sub-Saharan Africa,3.512,0.45100,0.73100,0.00700,2021
1079,Botswana,Sub-Saharan Africa,3.467,1.09900,0.72400,0.34000,2021
1080,Rwanda,Sub-Saharan Africa,3.415,0.36400,0.20200,0.40700,2021
1081,Zimbabwe,Sub-Saharan Africa,3.145,0.45700,0.64900,0.24300,2021
1082,Afghanistan,South Asia,2.523,0.37000,0.00000,0.12600,2021

In [ ]:
def normalize_with_percent(df):
    result = df1.copy()
    for feature_name in df1.columns:
        if df1[feature_name].dtype==float:
            # if dtype is float then normalize it
            max_value = df1[feature_name].max()
            min_value = df1[feature_name].min()
            result[feature_name] = ((df1[feature_name] - min_value) / (max_value - min_value))*100
    return result

In [ ]:
normalized_df1 = normalize_with_percent(df1)
print(normalized_df1)

          Country              Region  Happiness Score  \
0     Switzerland      Western Europe        95.205866
1         Iceland      Western Europe        94.717052
2         Denmark      Western Europe        94.077834
3          Norway      Western Europe        93.983832
4          Canada       North America        92.197782
...           ...                 ...              ...
1078      Lesotho  Sub-Saharan Africa        18.593721
1079     Botswana  Sub-Saharan Africa        17.747697
1080       Rwanda  Sub-Saharan Africa        16.770070
1081     Zimbabwe  Sub-Saharan Africa        11.693927
1082  Afghanistan          South Asia         0.000000

      Economy (GDP per Capita)  Family (Social Support)  \
0                    74.649113                82.086983
1                    69.614277                85.293796
2                    70.852272                82.760341
3                    77.989457                80.958029
4                    70.895570                80.450730
...                        ...                      ...
1078                 24.107776                44.464720
1079                 58.745999                44.038929
1080                 19.457274                12.287105
1081                 24.428500                39.476886
1082                 19.777998                 0.000000

      Health (Life Expectancy)  Year
0                    82.509202  2015
1                    83.070990  2015
2                    76.655565  2015
3                    77.581946  2015
4                    79.371604  2015
...                        ...   ...
1078                  0.613497  2021
1079                 29.798422  2021
1080                 35.670465  2021
1081                 21.297108  2021
1082                 11.042945  2021

[1083 rows x 7 columns]

In [ ]:
normalized_df1.to_csv('../data/processed/world_happiness_report_processed_Untitled.csv')